export { Alarma } from './Alarma'
export { Portada } from './Portada'
export { Hook } from './Hook'
export { Problema } from './Problema'
export { Reveal } from './Reveal'
export { Evidencia } from './Evidencia'
export { Demo } from './Demo'
export { Cierre } from './Cierre'
// Deck anterior (no usados en pitch 5 min)
// export { Dolencia1 } from './Dolencia1'
// export { Dolencia2 } from './Dolencia2'
// export { Actividades1 } from './Actividades1'
// export { VideoPanel } from './Video'
// export { Evolucion1 } from './Evolucion1'
// export { Evolucion2 } from './Evolucion2'
// export { Evolucion3 } from './Evolucion3'
// export { CTA } from './CTA'
